config/routes.rb
Pusher::Application.routes.draw do

  resources :flash_messages

  root :to => "flash_messages#index"
end

app/models/flash_message.rb
class FlashMessage < ActiveRecord::Base

  default_scope { order(:site) }
  
  Options = {error: "error", information: "information"}
  Site = {tv4: 'tv4', tv4play: 'tv4play'}


  def channel
  "site-#{site}-pusher"
  end

  def flash_type
    case message_type
      when 'error'
        'e'
      when 'information'
        'i'
      else
        'u'
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  before_filter :enforce_http_auth

  protected

  def enforce_http_auth
    return true unless Rails.env == 'stage' || Rails.env == 'production'

    authenticate_or_request_with_http_basic do |id, password|
      id == ENV['HTTP_AUTH_USER'] && password == ENV['HTTP_AUTH_PASSWORD']
    end
  end

end

app/controllers/flash_messages_controller.rb
class FlashMessagesController < ApplicationController
  before_action :set_flash_message, only: [:show, :edit, :update, :destroy]

  # GET /flash_messages
  def index
    @flash_messages = FlashMessage.all
  end

  # GET /flash_messages/new
  def new
    @flash_message = FlashMessage.new
  end

  # GET /flash_messages/1/edit
  def edit
  end

  # POST /flash_messages
  def create
    @flash_message = FlashMessage.new(flash_message_params)

    respond_to do |format|
      if @flash_message.save
        format.html { redirect_to flash_messages_path, notice: 'Meddelande sparades.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /flash_messages/1
  def update
    respond_to do |format|
      if @flash_message.update(flash_message_params)
        format.html { redirect_to flash_messages_path, notice: 'Meddelande uppdaterades' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /flash_messages/1
  def destroy
    @flash_message.destroy
    respond_to do |format|
      format.html { redirect_to flash_messages_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flash_message
      @flash_message = FlashMessage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flash_message_params
      params.require(:flash_message).permit(:message, :site, :message_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_messages_helper.rb
module FlashMessagesHelper
end

app/views/flash_messages/_form.html.haml
= form_for @flash_message do |f|
  - if @flash_message.errors.any?
    #error_explanation
      %h2= "#{pluralize(@flash_message.errors.count, "error")} prohibited this flash_message from being saved:"
      %ul
        - @flash_message.errors.full_messages.each do |msg|
          %li= msg

  %fieldset
    %legend= "Meddelande"
    .large-8.columns
      .row
        = f.label :message
        = f.text_field :message
    .large-2.columns
      .field
        = f.label :site
        = f.select :site, options_for_select(FlashMessage::Site,f.object.site)
    .large-2.columns
      .field
        = f.label :message_type
        = f.select :message_type, options_for_select(FlashMessage::Options,f.object.message_type)
  .actions
    = f.submit 'Spara', class: 'button large right'

app/views/flash_messages/edit.html.haml
.row
  %h1 Redigera meddelande

  = render 'form'

  %hr

  = link_to 'Tillbaka', flash_messages_path, class: 'button right secondary'

app/views/flash_messages/index.html.haml
%h1
  Sparade meddelanden

.row
  .large-12.columns
    %table.expand
      %thead
        %th.message Meddelande
        %th Site
        %th Typ
        %th
        %th
        %th

      - @flash_messages.each_with_index do |flash_message, index|
        %tbody
          %tr
            %td= flash_message.message
            %td{class: flash_message.site}
            %td= flash_message.message_type
            %td= link_to 'Editera', edit_flash_message_path(flash_message), class: 'button edit'
            %td= link_to 'Ta bort', flash_message, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'button alert'
            %td
              .button.publish{ onclick: "publishMessage(this,'#{flash_message.channel}' ,{ t: '#{flash_message.flash_type}', m: '#{flash_message.message}'})", id: "publish_button_#{index}"}
                = 'Publicera'


  %br

  = link_to 'Nytt meddelande', new_flash_message_path, class: 'button right new-message'

#pubnub{ origin: ENV['PUBNUB_HOST'], ssl: 'off',
  pub: { key: ENV['PUBNUB_PUBLISH_KEY'] },
  sub: { key: ENV['PUBNUB_SUBSCRIBE_KEY'] } }

= javascript_include_tag "//cdn.pubnub.com/pubnub-3.5.4.min.js"

app/views/flash_messages/new.html.haml
%h1 Nytt meddelande

= render 'form'

= link_to 'Tillbaka', flash_messages_path, class: 'button left secondary'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.top-bar
  %ul.title-area
    %li.name
      %h1
        %a{ href: root_path } Pusher
    %li.toggle-topbar.menu-icon
      %a{ href: "#" }
        %span Menu

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= "Pusher"
      %meta{:content => "Pusher", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    - if Rails.env != 'production'
      %div{ class: "env-bar stripes #{Rails.env}" }= Rails.env
    #container.container

      %header
        .row
          = render 'layouts/navigation'
          = render 'layouts/messages'
      #main{:role => "main"}
        .row
          = yield

    = javascript_include_tag "application"